Kleine Änderungen FrankencoinPay.com
FrankencoinPay/frankencoinpay.com pull request #10
Opened 2024-10-25 12:19 UTC by NoahDFX

2024-10-25 13:18 UTC, TaprootFreak commented on ecosystem.html
> -          <div class="text-block-2">Building something cool?</div>
das würde ich drin lassen

2024-10-25 13:19 UTC, TaprootFreak requested changes
Submit your project drin lassen

2024-10-25 13:25 UTC, NoahDFX commented on ecosystem.html
> -          <div class="text-block-2">Building something cool?</div>
@TaprootFreak Müsste jetzt wieder drin sein

2024-10-28 09:42 UTC, TaprootFreak approved these changes

2024-10-28 09:42 UTC, merged